// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// getEigen
SEXP getEigen(arma::mat M);
RcppExport SEXP _mmds_getEigen(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(getEigen(M));
    return rcpp_result_gen;
END_RCPP
}
// getEigenValue
arma::vec getEigenValue(arma::mat M);
RcppExport SEXP _mmds_getEigenValue(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(getEigenValue(M));
    return rcpp_result_gen;
END_RCPP
}
// getEigenVector
arma::mat getEigenVector(arma::mat M);
RcppExport SEXP _mmds_getEigenVector(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(getEigenVector(M));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mmds_getEigen", (DL_FUNC) &_mmds_getEigen, 1},
    {"_mmds_getEigenValue", (DL_FUNC) &_mmds_getEigenValue, 1},
    {"_mmds_getEigenVector", (DL_FUNC) &_mmds_getEigenVector, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mmds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
