# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEigen <- function(M) {
    .Call(`_mmds_getEigen`, M)
}

getEigenValue <- function(M) {
    .Call(`_mmds_getEigenValue`, M)
}

getEigenVector <- function(M) {
    .Call(`_mmds_getEigenVector`, M)
}

rcpparma_hello_world <- function() {
    .Call(`_mmds_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_mmds_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_mmds_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_mmds_rcpparma_bothproducts`, x)
}

