# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEigenValue <- function(M) {
    .Call(`_mmds_getEigenValue`, M)
}

getEigenVector <- function(M) {
    .Call(`_mmds_getEigenVector`, M)
}

getEigen <- function(M) {
    .Call(`_mmds_getEigen`, M)
}

